/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sprinkle;

/**
 *
 * @author septiandrd
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        minutes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        second = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        minutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesActionPerformed(evt);
            }
        });

        jLabel1.setText("Suhu");

        jLabel2.setText("Kelembaban");

        jLabel3.setText("Durasi");

        jLabel4.setText("C");

        jLabel5.setText("%");

        jLabel6.setText("Menit");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sprinkle");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        second.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondActionPerformed(evt);
            }
        });

        jLabel8.setText("Detik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        float suhu = Integer.parseInt(x.getText());
        float kelembaban = Integer.parseInt(y.getText());
        float tmp=0;  
        float mDingin=0;
        float mSejuk=0;
        float mNormal=0;
        float mHangat=0;
        float mPanas=0;
        float mKering=0;
        float mLembab=0;
        float mBasah=0;
        float mSingkat=0;
        float mSedang=0;
        float mLama=0;
        boolean dingin=false;
        boolean sejuk=false;
        boolean normal=false;
        boolean hangat=false;
        boolean panas=false;
        boolean kering=false;
        boolean lembab=false;
        boolean basah=false;

        if (suhu<=0) {
            mDingin = 1;
            dingin = true;
        } else if (suhu>0 && suhu<=3) {
            mDingin = (3-suhu)/3;
            mSejuk = (suhu-0)/3;
            dingin = true;
            sejuk = true;
        } else if (suhu>3 && suhu<=12) {
            mSejuk = 1;
            sejuk = true;
        } else if (suhu>12 && suhu<=15) {
            mSejuk = (12-suhu)/3;
            mNormal = (suhu-12)/3;
            sejuk = true;
            normal = true;
        } else if (suhu>15 && suhu<=24) {
            mNormal = 1;
            normal = true;
        } else if (suhu>24 && suhu<=27) {
            mNormal = (27-suhu)/3;
            mHangat = (suhu-24)/3;
            normal = true;
            hangat = true;
        } else if (suhu>27 && suhu<=36) {
            mHangat = 1;
            hangat = true;
        } else if (suhu>36 && suhu<=39) {
            mHangat = (39-suhu)/3;
            mPanas = (suhu-36)/3;
            hangat = true;
            panas = true;
        } else {
            mPanas = 1;
            panas = true;
        }      

        if (kelembaban<10) {
            mKering = 1;
            kering = true;
        } else if (kelembaban>10 && kelembaban<=20) {
            mKering = (20-kelembaban)/10;
            mLembab = (kelembaban-10)/10;
            kering = true;
            lembab = true;
        } else if (kelembaban>20 && kelembaban<=40) {
            mLembab = 1;
            lembab = true;
        } else if (kelembaban>40 && kelembaban<=50) {
            mLembab = (50-kelembaban)/10;
            mBasah = (kelembaban-40)/10;
            lembab = true;
            basah = true;
        } else {
            mBasah = 1;
            basah = true;
        }

        if (kering) {
            if (dingin) {        
                mLama = Math.min(mKering,mDingin);
            }
            if (sejuk) {
                if (mLama<Math.min(mKering,mSejuk)) {
                    mLama = Math.min(mKering,mSejuk);
                }
            }
            if (normal) {
                if (mLama<Math.min(mKering,mNormal)) {
                    mLama = Math.min(mKering,mNormal);
                }
            }
            if (hangat) {
                if (mLama<Math.min(mKering,mHangat)) {
                    mLama = Math.min(mKering,mHangat);
                }
            }
            if (panas) {
                if (mLama<Math.min(mKering,mPanas)) {
                    mLama = Math.min(mKering,mPanas);
                }
            }
        }

        if (lembab) {
            if (dingin) {
                mSingkat = Math.min(mLembab,mDingin);
            }
            if (sejuk) {
                if (mSingkat<Math.min(mLembab,mSejuk)) {
                    mSingkat = Math.min(mLembab,mSejuk);
                }
            }
            if (normal) {
                if (mSingkat<Math.min(mLembab,mNormal)) {
                    mSedang = Math.min(mLembab,mNormal);
                }
            }
            if (hangat) {
                if (mSingkat<Math.min(mLembab,mHangat)) {
                    mSedang = Math.min(mLembab,mHangat);
                }
            }
            if (panas) {
                if (mSingkat<Math.min(mLembab,mPanas)) {
                    mSedang = Math.min(mLembab,mPanas);
                }
            }
        }

        if (basah) {
            if (dingin) {
                mSingkat = Math.min(mBasah,mDingin);
            }
            if (sejuk) {
                if (mSingkat<Math.min(mBasah,mSejuk)) {
                    mSingkat = Math.min(mBasah,mSejuk);
                }
            }
            if (normal) {
                if (mSingkat<Math.min(mBasah,mNormal)) {
                    mSingkat = Math.min(mBasah,mNormal);
                }
            }
            if (hangat) {
                if (mSingkat<Math.min(mBasah,mHangat)) {
                    mSingkat = Math.min(mBasah,mHangat);
                }
            }
            if (panas) {
                if (mSingkat<Math.min(mBasah,mPanas)) {
                    mSingkat = Math.min(mBasah,mPanas);
                }
            }
        }

        tmp = ((mSingkat*20) + (mSedang*40) + (mLama*60)) / (mSingkat+mSedang+mLama); 
        System.out.println(mSingkat);
        System.out.println(mSedang);
        System.out.println(mLama);
        long detik = (long) Math.ceil(tmp*60);
        long menit = detik/60;
        detik = detik % 60;
        minutes.setText(menit+"");
        second.setText(detik+"");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void minutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutesActionPerformed

    private void secondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField minutes;
    private javax.swing.JTextField second;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
